spring:
  application:
    name: corralon

  datasource:
    # Los valores por defecto (:localhost, :3306, etc.) se usan solo
    # si se corre la app local con mvn spring-boot:run.
    # Con Docker, las variables se inyectan desde compose.yaml.
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:corralon_db}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${MAIL_AUTH:false}
          starttls:
            enable: ${MAIL_STARTTLS:false}

  app:
    base-url: ${APP_BASE_URL:http://localhost:8080}

  jwt:
    secret: QzY1RjQ4QjQzRjQ3RjQ2RjQ1RjQ0RjQzRjQyRjQxRjQwRjM5RjM4RjM3RjM2RjM1RjM0RjMzRjMyRjMxRjMwRjI5RjI4RjI3RjI2RjI1RjI0RjIzRjIyRjIxRjIwRjE5RjE4RjE3RjE2RjE1RjE0RjEzRjEyRjExRjEwRjA5RjA4RjA3RjA2RjA1RjA0RjAzRjAyRjAxRjAw

  expiration: 86400000

server:
  port: 8081
