spring:
  application:
    name: corralon

  datasource:
    # Los valores por defecto (:localhost, :3306, etc.) se usan solo
    # si se corre la app local con mvn spring-boot:run.
    # Con Docker, las variables se inyectan desde compose.yaml.
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:corralon_db}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: "Fp9vB7EaDnMYPhq7LxxiXIwb07pcLDBZoyzVrnJFWqy"
  expiration: 86400000

server:
  port: 8081
