package com.utn.corralon.features.product.mapper;

import com.utn.corralon.features.brand.entity.BrandEntity;
import com.utn.corralon.features.category.entity.CategoryEntity;
import com.utn.corralon.features.product.dto.ProductRequestDTO;
import com.utn.corralon.features.product.dto.ProductResponseDTO;
import com.utn.corralon.features.product.entity.ProductEntity;
import com.utn.corralon.features.supplier.entity.SupplierEntity;
import org.modelmapper.Converter;
import org.modelmapper.ModelMapper;
import org.modelmapper.spi.MappingContext;
import org.springframework.stereotype.Component;

@Component
public class ProductMapper {

    private final ModelMapper modelMapper;

    public ProductMapper(ModelMapper modelMapper) {
        this.modelMapper = modelMapper;

        // Define a custom converter for ProductRequestDTO to ProductEntity
        Converter<ProductRequestDTO, ProductEntity> requestDtoToEntityConverter = new Converter<ProductRequestDTO, ProductEntity>() {
            @Override
            public ProductEntity convert(MappingContext<ProductRequestDTO, ProductEntity> context) {
                ProductRequestDTO source = context.getSource();
                // If destination is null, create a new instance; otherwise, update the existing one
                ProductEntity destination = context.getDestination() != null ? context.getDestination() : new ProductEntity();

                // Manually map properties, explicitly avoiding setId()
                // The ID will be generated by the persistence layer or set by the service
                destination.setName(source.getName());
                destination.setDescription(source.getDescription());
                destination.setActive(source.getActive());

                // Related entities (Supplier, Category, Brand) are handled by the service layer
                // and are not mapped directly from their IDs in the DTO here.
                // ModelMapper will not attempt to set them implicitly.

                return destination;
            }
        };

        // Register the custom converter for the specific type pair
        modelMapper.addConverter(requestDtoToEntityConverter);

        // For ProductEntity to ProductResponseDTO, we can still rely on implicit mapping
        // or add specific configurations if needed, but it's not the source of the current error.
    }

    public ProductResponseDTO toResponse(ProductEntity product) {
        // This mapping is from ProductEntity to ProductResponseDTO, not affected by the above converter
        return modelMapper.map(product, ProductResponseDTO.class);
    }

    public ProductEntity toEntity(ProductRequestDTO dto,
                                  SupplierEntity supplier,
                                  CategoryEntity category,
                                  BrandEntity brand) {
        // This will now use the custom converter registered above
        ProductEntity product = modelMapper.map(dto, ProductEntity.class);

        // Manually set the related entities after the DTO mapping
        product.setSupplier(supplier);
        product.setCategory(category);
        product.setBrand(brand);

        return product;
    }

    public void updateEntity(ProductEntity product,
                             ProductRequestDTO dto,
                             SupplierEntity supplier,
                             CategoryEntity category,
                             BrandEntity brand) {
        // This will also use the custom converter, mapping dto onto the existing product
        modelMapper.map(dto, product);

        // Manually update the related entities after the DTO mapping
        product.setSupplier(supplier);
        product.setCategory(category);
        product.setBrand(brand);
    }
}